# Write u'r server name
server_prefix: 'FicureConfig'
#Customize plugin messages
vanishenabled: 'Vanish mode enabled!'
vanishdisabled: 'Vanish mode disabled!'
setvanishenabled: 'You enabled vanish for the '
setvanishdisabled: 'You disabled vanish for the '



# ALL PERMISSIONS
# /spawnboss - ficure.spawnboos
# /me - ficure.me
# /kit start / medium / maximum - ficure.kitstart / ficure.kitmedium / ficure.kitmaximum / ficure.kitmaximum
# /feed - ficure.feed
# /heal - ficure.heal
# /setfood - ficure.setfood
# /sethealth - ficure.sethealth
# /clear FunctionsCHAT - ficure.clearchat
# /calculate - ficure.calculate
# /broadcast - ficure.broadcast
# /vanish -> vanish.vanish
# /setvanish -> vanish.setvanish