name: Ficure
version: '${project.version}'
main: ts.ralexme.ficure.Ficure
api-version: '1.16'
description: Ficure is a STILL simple plugin for u'r minecraft server, but it will/have many interesting features!
commands:


#--------------AAAAAAAAA-------0000----------------------------------------------------------------#
#--------------A-------A------0---0----------------------------------------------------------------#
#--------------A-------A-----0----0----------------------------------------------------------------#
#--------------AAAAAAAAA----------0----------------------------------------------------------------#
#--------------A-------A----------0----------------------------------------------------------------#
#--------------A-------A----------0----------------------------------------------------------------#
#--------------A-------A------000000000------------------------------------------------------------#

  #A1_Commands
  clear:
    description: It will clear the chat on the server!
    aliases: cl
    usage: /clear chat

  calculate:
    description: It will calculate, u can use (+|-|/|*) for calculating!
    aliases: calc
    usage: /calculator ( num1 | + or - or / or * | num2) for calculating

  me:
    description: You can show u'r reaction for friends!
    usage: /me <Hello | GoodBye | WhatsUp>

  spawnBoss:
    description: Spawns only four, favorite mobs(type\ boss) - EnderMan, Wither, Creeper!
    usage: /spawnBoss <enderman | wither | creeper | skeleton>

  kit:
    description: Give's for the player kit (start, medium, maximum)
    usage: /kit <start, medium, maximum>

  setfood:
    description: Set food to Player!
    usage: /setfood <playerName> <FoodLevel>

  sethealth:
    description: Set food to Player!
    usage: /sethealth <playerName> <HealthLevel>


#--------------BBBBBBBB------- 0000----------------------------------------------------------------#
#--------------B-------B------0---0----------------------------------------------------------------#
#--------------B-------B-----0----0----------------------------------------------------------------#
#--------------BBBBBBB------------0----------------------------------------------------------------#
#--------------B-------B----------0----------------------------------------------------------------#
#--------------B-------B----------0----------------------------------------------------------------#
#--------------BBBBBBBB-------000000000------------------------------------------------------------#

    #B1_Commands
  heal:
    description: Heals you when you want!
    usage: /heal

  feed:
    description: Feed you when you want!
    usage: /feed

  broadcast:
    description: Broadcast u'r messages for the server
    aliases: br
    usage: /broadcast <message>


  #--------------------------------------------------------------------------------------------------#
  #--------------------------------------------------------------------------------------------------#
  #---------------------------------------TESTCMD's--------------------------------------------------#
  #--------------------------------------------------------------------------------------------------#
  #--------------------------------------------------------------------------------------------------#

  test:
    description: Tests chatcolor function
    usage: ERROR, if you see this message (if) didn't work )))
  test2:
    description: Test second type of chatcolor
    usage: ERROR, if you see this message (if) didn't work )))


    #--------------------------------------------------------------------------------------------------#
    #--------------------------------------------------------------------------------------------------#
    #------------------------------------TECHNICAL CMD's-----------------------------------------------#
    #--------------------------------------------------------------------------------------------------#
    #--------------------------------------------------------------------------------------------------#

  reloadFicure:
    description: Reloads Ficure - config.yml
    usage: /reloadFicure